### ISSUE TITLE
Workers passwords field is to small

### ISSUE THREAD

**Issue by Getron** [MPOS/php-mpos#2377]
Hi

Im on a pool with new version now, but, the password of workers fields are to small. Can you please make this field larger? And "Worker Login" name smaller. Maybe, the width should be in %? On bigger screens, the worker name (Worker Login) field is too big (%), and the password field to small (pixel).

Please, check this "Worker Configuration", for example, at 2560x1600 screen resolution, and you will see the problem.

Thanks

Regards

Joe

**Comment by TheSerapher** [comment]
Hey @Getron,

Sorry for not getting back to you earlier. Been busy in RL quite a bit.

I don't remember for sure, but I think it was bound to pixels because otherwise the formatting was lost. I may be wrong on this one though.

If someone could take a look and make sure it works under different resolutions that would be great. It may be a while before I have a working test setup again.

**Comment by Getron** [comment]
Hi @TheSerapher,

You can use the resolution simulator, for example, here: http://quirktools.com/screenfly to test the site and design at all resolutions, on all mobiles, etc.

**Comment by TheSerapher** [comment]
I won't have to to dig deeper for this. I remember it had something to do with he CSS for that box surround the words. I played with that for a while but didn't make it do what I wanted.

If someone wants to take a stab at it feel free. Just make sure other inputs aren't negatively affected by the change.

**Comment by TheSerapher** [comment]
I tried to replicate your issue, but I have none with larger resolutions (running MacBook scaled up to biggest screen size). I do see issues with smaller screens since the Worker Prefix (e.g. TheSerapher.) is taking up most of the room.

I don't see this as a large issue though, workers are usually setup once and not really touched anymore after that.

**Comment by TheSerapher** [comment]
Thanks to @nrpatten, a new `mpos.css` is now in the development branch that fixes this.
