### ISSUE TITLE
Payouts disabled?

### ISSUE THREAD

**Issue by pandaloco** [MPOS/php-mpos#2378]
i have this issue Payouts disabled, you will not receive any coins to your offline wallet for the time being

i keep getting Wallet does not cover payouts total amount

even tho i sent coins to the wallet and nothing i rund the payouts.php, run_payouts.sh i even tried the -f and when i run with -f i get Wallet does not cover payouts total amount i checked the logs it says the same thing Wallet does not cover payouts total amount, heres a screenshoot http://i.imgur.com/iViv6vz.jpg 

i went to similar issues on this site but non of them have been resolve and yeah dont send me to IRC channel coz am alrady there waiting for someone to answer ...

**Comment by TheSerapher** [comment]
Probably coins in an account and MPOS not able to pick on the account address that holds the coins. Try moving them around your local addresses.

Each coin daemon acts differently so can't be sure what it is. And due to lack of time it's not something that will be fixed in MPOS unless someone is able to open a PR for it.
