### ISSUE TITLE
MPOS not distribute coins

### ISSUE THREAD

**Issue by everycrypto** [MPOS/php-mpos#2384]
![monitoring](https://cloud.githubusercontent.com/assets/8829627/5956960/a761a84e-a7b3-11e4-9a2d-32c0f3ed7bfe.jpg)

hi

i did reboot but MPOS not distribute coins.
There are operations to do throwing with putty ?

**Comment by TheSerapher** [comment]
As a reminder, NEVER reboot a server with crons being active. ALWAYS disable all cron in the crontab, then wait until they complete and reboot.

I am assuming you checked the log files and searched for a solution on this Repo.

Quick search on the repo with 'reboot' as the search term revealed this: https://github.com/MPOS/php-mpos/issues/1566

**Comment by everycrypto** [comment]
thanks for the reply, what can you tell me about the picture ... is entirely accurate or the red box says something wrong?

**Comment by TheSerapher** [comment]
Looks fine to me, cron are marked as running fine (OK) are not disabled (X) and ran successfully. Not sure if the timestamps are good or not.

These will indicate too if something is wrong. If your timestamps start to drift off, they first turn yellow, then red if it has been too long since the cron job ran.

Ensure cron are setup, no errors are logged and you actually found any blocks (which you haven't since the block update ran).

**Comment by everycrypto** [comment]
I did not understand anything ... thanks for taking your time
maybe a simple answer YES is in place ... it was appreciated

also for the previous ... I have not solved anything
MPOS returns coins, so the problem is open and can not be closed ...
p.s .: as usual I go where you send all: IRC

**Comment by everycrypto** [comment]
so to speak: the log files are ... 10 ... if you do not have time to devote to ... avoids wasting time

**Comment by TheSerapher** [comment]
I am on IRC right now.
