### ISSUE TITLE
api call for a complete list of pool workers

### ISSUE THREAD

**Issue by jjj092353** [MPOS/php-mpos#2389]
is there an api call for a complete list of pool workers and their hash rates - I know I can get it for each worker but I have a need to get a complete list of all pool workers - is there an admin api key and call that will give me this?

thanks

**Comment by jjj092353** [comment]
"active pool workers" please...

**Comment by TheSerapher** [comment]
This was added before for the admin pages to show a list of all workers currently active on the pool. It was changed to show only a limited amount of workers due to the excessive load this caused on a database.

I won't add this globally for everyone, but using https://github.com/MPOS/php-mpos/blob/master/include/pages/admin/poolworkers.inc.php#L16 with a very high limit and converting it to JSON output you could add this yourself.
