### ISSUE TITLE
Network hashrate calculation

### ISSUE THREAD

**Issue by sburina** [MPOS/php-mpos#2398]
Hi!

By default, a wallet method "getmininginfo" returns the average hash rate for the number of blocks targeted for 24 hours (if developer coded it correctly, which is not always the case). However, there's also a method "getnetworkhashps" which can accept additional parameter - the number of blocks to take into account, or -1 to look since the last difficulty change onwards.

Can you please tell me which method MPOS uses and/or can it show the network hashrate based on user-configured number of blocks (or -1)?

Thank you!

**Comment by TheSerapher** [comment]
MPOS wraps the standard RPC call supplied in the bitcoin class/RPC with some "catchall" methods to figure out what the network hash rate is: https://github.com/MPOS/php-mpos/blob/master/include/classes/bitcoinwrapper.class.php#L69-L96

As you can see, we are calling `getmininginfo` in the RPC since this is the most useful and just decide on the array keys available where to read that information. This means the call `getnetworkhashps` is wrapper for all coins into that multi-call. If you want to change it to match your specific need, feel free to do so :-)
