### ISSUE TITLE
Shared Database On External MySQL Server

### ISSUE THREAD

**Issue by daygle** [MPOS/php-mpos#2416]
Just wondering if there are any plans to enable shared database on a non-local machine? I have multiple pools installed on individual servers and this feature would be very handy (I'm sure others would like this too):-

I would imagine the settings would look this this if it was possible:-

$config['db']['shared']['host'] = 'externalhost';
$config['db']['shared']['user'] = 'someuser';
$config['db']['shared']['pass'] = 'somepass';
$config['db']['shared']['port'] = 3306;
$config['db']['shared']['name'] = 'mpos';

**Comment by TheSerapher** [comment]
The current implementation does not allow for a secondary backend. It requires a lot of code changes, especially how databases are handled, to make it work.

I keep this open since I already played around with it, but in the meantime consider using features supplied by MySQL to link these databases into other instances.

**Comment by suchpool** [comment]
Like TheSerapher said, you may use the MySQL federated plugin to load up remote tables into a local database to use as shared. This may require a lot of bandwidth depending on the size of your tables.

**Comment by TheSerapher** [comment]
I actually just meant to copy the `<somepool>.coin_addresses` table into `<sharedDB>.coin_addresses`. It was not mentioned in the Wiki and was an oversight on my side. Doing that should fix it :-)
