### ISSUE TITLE
Payouts disabled !!!

### ISSUE THREAD

**Issue by jam3oun** [MPOS/php-mpos#2418]
hello , i create a pool with stratum and MPOS , pool works perfectly , it collect coin but my only problem is i can't send coin to the wallet this is the problem !!!

"We are investingating issues in the backend. Your shares and hashrate are safe and we will fix things ASAP.
Payouts disabled, you will not receive any coins to your offline wallet for the time being"

How can i fixed this problem pleaze !!! 

![capture du 2015-05-05 183](https://cloud.githubusercontent.com/assets/11738856/7478261/727b6e3c-f351-11e4-8d8a-c0c0d34ff97e.png)

**Comment by TheSerapher** [comment]
Check your log files for the payout cron, probably not able to cover the coin payouts with the available balance.

**Comment by jam3oun** [comment]
the log files alwayes want me to force payout cron with -f !! i forcet it with -f and the same probleme !

and i have a 5 TTC i think i can send them to the wallet !!!

**Comment by TheSerapher** [comment]
You didn't scroll back in the log to find the actual error message of the cron.

**Comment by TheSerapher** [comment]
Oh you edited. So there you go, wallet value does not cover your requested payout. Check if it may not be confirmed in the wallet or simply missing.

**Comment by jam3oun** [comment]
see that !!!
![capture](https://cloud.githubusercontent.com/assets/11738856/7492608/81b85932-f3f1-11e4-8930-ca7cfff7f963.png)

i have 6 coin mined and i can't send them !! 
but the liquid assets -6 ! 
What's the problem ? how resolve that !

**Comment by TheSerapher** [comment]
No idea, seems like you have found some blocks but they were not paid into the wallet at all. Try to find help for the person creating your coin daemon, this is not something that can be fixed in MPOS.

MPOS found blocks in your wallet, added those to the database and paid the users. The wallet on the other hand does not show the discovered blocks balance at all. Maybe the blocks have been added to a wrong wallet account (MPOS pays out ONLY from the default account `""`). You can check your local coind accounts where the money went and transfer them to the address associated to your default account.

**Comment by jam3oun** [comment]
My system of payout is PPS ( pay per share ) and i don't have any block in my pool.
it is necessary to have a block to send money to the wallet ? 
i think with PPS i can send them without finding a block !

**Comment by TheSerapher** [comment]
Sigh ... As the documentation states: DO NOT RUN PPS UNLESS YOU KNOW WHAT YOU ARE DOING.

Reason: PPS pays all miners UP FRONT. You will receive coins right away even though NO BLOCK IS FOUND. If you have no coins to buffer for long rounds (blocks take longer than expected to be discovered) you have to pay miners out of your own pocket.

Coins do not magically appear from nowhere. You either send coins to the wallet yourself or mine a couple blocks yourself without paying out.

You can send coins to your mining wallet at any time, it does not require the wallet to find a block for that. So fill up that wallet and then you are fine.

But a warning: PPS is dangerous - get a couple long rounds with people mining coins and you have to pay them from your own coins. If your pool dies due to a long round, you will be out of coins and have a lot of pissed miners at  hand.

**Comment by jam3oun** [comment]
So i should have a wallet balance > locked for user , to have a positive liquid assets and to can send coin to the wallet ???

I just put PPS as a system of payement because i alwayes mine and i can't find a block i don't have a chance because i mine with my personel computer just with 1 worker.

**Comment by TheSerapher** [comment]
Sigh ... No blocks, no coins. Even PPS does not change that. It's a system to give users coins per share, but the pool operator has to pay these coins out of their own pocket if no block is found.

Don't run a pool yourself then. If you don't have the hashing power to do it, don't do it. Join any existing pool and mine there.

PPS is NOT what you think it is, so don't use it.

Case closed.

**Comment by jam3oun** [comment]
THX for your help.  
but i mine by my self because i configure a local pool with ubuntu and i want test it if the pool work perfectly i will share the pool in a VPS server and collect many users !!

**Comment by TheSerapher** [comment]
Then word of advice: Don't run PPS. You don't seem to have grasped the concept and I would not like to see pissed of miners due to that :-)

Run PPLNS, it's the fairest system. You don't find a block yourself but at least you won't run into those issues.

**Comment by jam3oun** [comment]
ok i will change to PPLNS thanks a lot THESERAPHER :))) 
my speed of hashrate is between [ 10.. 17 ] Kh/s with this speed can i find a block ?

**Comment by TheSerapher** [comment]
Don't forget to reset the pool to 0 before changing :-)

No, you probably won't find one. Depends on the difficulty of the coin of course. Use online hash rate calculators (http://www.coinwarz.com/calculators) to figure that out.

**Comment by jam3oun** [comment]
thx and i don't have a chance :(( i will add my friends to can find a block
