### ISSUE TITLE
favicon mpos

### ISSUE THREAD

**Issue by pisman3** [MPOS/php-mpos#2437]
help set the favicon in mpos

**Comment by pisman3** [comment]
master.tpl
added two lines did not help
<link rel="shortcut icon" href="http://188.166.126.160/favicon.ico" />
<link rel="shortcut icon" href="favicon.ico" />

**Comment by TheSerapher** [comment]
It's already set. You just have to upload the proper picture into the public document root.

**Comment by pisman3** [comment]
I did so on the link seen

**Comment by pisman3** [comment]
It does not appear for some reason

**Comment by TheSerapher** [comment]
Not sure, but it is requested:
{noformat}
Remote Address:188.166.126.160:80
Request URL:http://188.166.126.160/favicon.ico
{noformat}

So maybe an icon issue or something else, definitely not an issue with MPOS.

**Comment by pisman3** [comment]
![favicon](https://cloud.githubusercontent.com/assets/12834050/8162546/aa915372-1386-11e5-9b11-7d2bd514f566.png)

**Comment by pisman3** [comment]
not properly signed

**Comment by TheSerapher** [comment]
Works fine in Firefox, so it's some client issue that I can't help you with.

**Comment by TheSerapher** [comment]
Also seems to work in Chrome.

**Comment by TheSerapher** [comment]
Screenshots:

![screen shot 2015-06-15 at 16 50 46](https://cloud.githubusercontent.com/assets/2376835/8162610/bbd5fac8-137e-11e5-9e90-6c29c0c1d704.png)
![screen shot 2015-06-15 at 16 50 56](https://cloud.githubusercontent.com/assets/2376835/8162611/bbf2d3fa-137e-11e5-96d6-15ff3e4577b8.png)

**Comment by pisman3** [comment]
everything works

**Comment by TheSerapher** [comment]
For future reference, please refrain from opening issues for every single bit that doesn't seem to work. This issue tracker is for bug reports and actual issues with the software, not client side setup issues that could be fixed by using Google most of the time.

You can also try finding IRC Chat Channels either on Freenode (see link in Documentation/Wiki) or in your local language.

I also still recommend not setting up a pool for live traffic. You are bound to run into issues that will not be solved by opening a ticket here and asking for help.

**Comment by pisman3** [comment]
browser cache must

**Comment by pisman3** [comment]
Thank you to help
