### ISSUE TITLE
Stats on Dashboard not updating (frozen)

### ISSUE THREAD

**Issue by mmitech** [MPOS/php-mpos#2457]
The stats on Dashboard are not updating (refreshing), I also can't see any workers, everything is set to the minimum in the statistic page (5sec, 5 sec, 1min) and this is what I still see after 10 mins http://i.imgur.com/exMjnJb.png

 I believe this happened after I upgraded to the latest version, After some investigation I get this when I try to run  run-statistics.sh: 
PHP Fatal error:  Call to undefined method mysqli_stmt::get_result() in /var/www/html/MPOS/include/classes/base.class.php on line 174

can you please assist me. Thank you.

**Comment by TheSerapher** [comment]
That's not an MPOS issue. You do not run mysql-nd on your server. See requirements and quick start guide.

These lines are called from upstream mysqlnd and cause your issue: https://github.com/MPOS/php-mpos/blob/master/include/classes/base.class.php#L173-L174

**Comment by mmitech** [comment]
yes I figured that out and fixed it, but stats are still not working !! and I can't seem to understand what is wrong, in fact I will retract what I said about upgrading causing this issue, because an upgrade in another pool didn't cause this problem.

so any other suggestions ?

**Comment by TheSerapher** [comment]
Check if your API is blocking it. By default, requests to the API are throttled by IP. You can change the settings in your `security.inc.php` file.

Also check you don't have clashing memcache keys. And of course check any custom code you may have added.

Since it's only for a single site, it has to be a setup issue. Can't go through all options as you may be able to imagine, but those would be the ones I'd check for.

**Comment by mmitech** [comment]
Thank you, Fixed.. it was memcache as you suggested.
