### ISSUE TITLE
sso authentication, cookie

### ISSUE THREAD

**Issue by keepthefaya** [MPOS/php-mpos#2464]
hi, Is it logical to find all of the workers when applied sso authentication?

$config['db']['host'] = '127.0.0.1';
$config['db']['user'] = 'globaluserdatabase';
$config['db']['pass'] = 'supermysqlpassword';
$config['db']['port'] = 3306;
$config['db']['name'] = 'mpos_global';
// Disabled by default and set in bootstrap if unset, but left in here so
// people know it exists
$config['db']['shared']['accounts'] = $config['db']['name'];
$config['db']['shared']['workers'] = $config['db']['name'];
$config['db']['shared']['news'] = $config['db']['name'];

Thanks for your feedback

**Comment by TheSerapher** [comment]
Yes because workers are a simple user/pass thing. You don't have to share workers, but it makes logging in across different stratums easier. Only thing is that these stratum needs a code update in order to change where they look for worker information (instead of the default database used where coin shares are stored, they need to check in the shared DB). Simple change for most implementations

In the end, even though the workers are shared across all pools, they will all show the pool specific hash rates. Those come from the shares table, which isn't shared and specific to a pool.

**Comment by TheSerapher** [comment]
Also you setup is not properly done for SSO if I am not mistaken. You point by default to a global DB name, which you shouldn't. This should be the specific pool DB (for shares etc.).

You should use this:

```
$config['db']['host'] = '127.0.0.1';
$config['db']['user'] = 'globaluserdatabase';
$config['db']['pass'] = 'supermysqlpassword';
$config['db']['port'] = 3306;
$config['db']['name'] = 'pos_coin_specific';
// Disabled by default and set in bootstrap if unset, but left in here so
// people know it exists
$config['db']['shared']['accounts'] = 'mpos_global.accounts';
$config['db']['shared']['workers'] = 'mpos_global.workers';
$config['db']['shared']['news'] = 'mpos_global.news';
```

**Comment by keepthefaya** [comment]
thanks so much it works !

**Comment by keepthefaya** [comment]
toutefois il reste un problème parce que si on laisse :

$config['db']['host'] = '127.0.0.1';
$config['db']['user'] = 'globaluserdatabase';
$config['db']['pass'] = 'supermysqlpassword';
$config['db']['port'] = 3306;
$config['db']['name'] = 'mpos_coin_specific';
// Disabled by default and set in bootstrap if unset, but left in here so
// people know it exists
$config['db']['shared']['accounts'] = 'mpos_global';
$config['db']['shared']['workers'] = 'mpos_global';
$config['db']['shared']['news'] = 'mpos_global';

On ne peut pas consulter sur l'écran de contrôle des stats et les informations, l'affichage pointant vers "mpos_coin_specific". Mes statistiques restent vident....

have you ever had this trouble?

**Comment by TheSerapher** [comment]
Yes but those were related to wrong Memcache settings missing proper key prefixed or host entries so the statistics got mixed up between pools.

I will check my development setup which works fine but I am pretty sure the config is correct. I will update the documentation once I find something wrong.

Maybe someone else already running SSO can chime in.

**Comment by keepthefaya** [comment]
For memcache (global.inc.php), what configuration you will apply on "keyprefix"?

**Comment by TheSerapher** [comment]
Maybe take a screenshot to explain your problem. I assume you are French and Google Translate isn't the best to covey technical information ;-)

**Comment by TheSerapher** [comment]
Make the key prefix coin specific for each pool so the caches are properly filled with only pool specific data.

**Comment by keepthefaya** [comment]
http://oi62.tinypic.com/dp8g34.jpg

**Comment by TheSerapher** [comment]
Each pool needs its on specific database. Then you need a global for the global tables as listed in the Wiki (accounts, workers, coin_addresses, news ...). Once you send a worker to one pool it shouldn't show as hashing on the other pools. Shares should only be inserted to the pool specific shares table. If that's not the case then the setup isn't right (global database should never have any shares in it).

Please keep In mind this can work it's not officially supported by any of the stratum daemons. Unless you have coding experience I do not recommend running a SSO setup since MPOS is onto one part of it. Until you fix Stratum to support a global worker table for each coin and use the specific shares table for shares you won't make it work.

Stratum coding is out of scope of this setup though and I can't help you on that.

**Comment by keepthefaya** [comment]
thank for you back, my bad wrong config in specific_coin.json for mysql ..... it works!
