### ISSUE TITLE
Showing H/s for scrypt adaptive coins

### ISSUE THREAD

**Issue by mmitech** [MPOS/php-mpos#2467]
The N factor in some scrypt-jane coins can raise to a point where the graphics cards will generate less than 1KH/s hashrate, most miners will have 0 KH/s on the dashboard... so I tried to change that in MPOS by changing the next line in include/config/admin_settings.inc.php and  include/smarty_globals.inc.php

    ( '1' => 'H/s', '0.001' => 'KH/s', '0.000001' => 'MH/s', '0.000000001' => 'GH/s', '0.000000000001' => 'TH/s'  ),

however, when I change it in smarty_globals.inc.php the site just crash and returns internal server error 500 !

any Idea on how can I achieve that without breaking the pool ?

**Comment by TheSerapher** [comment]
You probably made a syntax error. Check the Apache logs on what's causing the 500.

I don't know if there could be a more elegant solution than fixing that file but this would work for those funny coins. I probably won't have time to look into detail why they behave like that. Vacation for two weeks and not available after I leave my hotspot.

**Comment by mmitech** [comment]
I found the syntax error but that what I changed doesn't really fix the issue, the same hashrate is shown with but instead of KH/s there is H/s, if you increase it to KH/s it will show the hashrate as if it was MH/s and so on.

 enjoy your vacations, you deserve it :+1:

**Comment by TheSerapher** [comment]
That's because the SQL queries already return khash. It would need to return data in hashes/s to make this work. This could also be a potential generic solution. Just run hashes/s internally and let the presentation decide what to display.

**Comment by TheSerapher** [comment]
Back from vacation :-)

Found how that worked: https://github.com/MPOS/php-mpos/blob/master/include/classes/statistics.class.php#L500

It calls a coin specific modifier for the hash rate (e.g. https://github.com/MPOS/php-mpos/blob/master/include/classes/coins/coin_base.class.php#L54-L56). Other coins can overwrite this to implement their own calculations. Most don't change it so the default of khash is used.

So in order for this to work for your specific coin we need a new coin class (scrypt-jane?) and change how the hash rate is calculated. Not sure how that will affect the display of hash rates but I'd guess the modifiers will need to be adjusted too.

Or we make hashes/s the default in base class and adjust the display method in smarty_globals for it. Again this may affect old pools running for a while since now all statistics will be stored as hashes/s instead of khash/s.

Not an easy thing to do since it will affect basically all running pools unless we find a clean way to do it without affecting stats (or having to update the stats tables via SQL which could also work).

**Comment by mmitech** [comment]
Welcome back :)

I will look at it later, it sure need some work around, I will try to figure it out later when I have time for  and update you.

Thank you.

**Comment by TheSerapher** [comment]
Old ticket here but is this still something to pursue or should it be closed?

**Comment by mmitech** [comment]
Sorry nothing to follow, I forgot to close it, I didn't look into it anymore (just lost interest).

**Comment by TheSerapher** [comment]
No worries :)
