### ISSUE TITLE
Add an N*Diff PPLNS reward variant

### ISSUE THREAD

**Issue by jonnybravo0311** [MPOS/php-mpos#2488]
The current PPLNS offerings available are "blockavg", "dynamic" or "fixed".  I'd like to add another one to the mix: an N times current block difficulty.  This would require two changes.  The first is an addition to the global.inc.php file as follows:

`$config['pplns']['ndiff']['blockcount'] = X;` Where X is a number of blocks to consider

The second is a change to the pplns_payout cron adding the following:

`else if ($config['pplns']['shares']['type'] == 'ndiff' && $block->getBlockCount() > 0) {
    $pplns_target = round($aBlock['difficulty'] * $config['pplns']['diff']['blockcount']);
}`

For example, to configure a 5N difficulty, a user would choose `$config['pplns']['shares']['type'] = 'ndiff';` and `$config['pplns']['ndiff']['blockcount'] = 5;`

**Comment by TheSerapher** [comment]
Hey @jonnybravo0311,

It's been a while that I have done any mining but wouldn't your system mean that you potentially overpay users since you are looking at expected block difficulties all the time? If you had 5 lucky rounds and you still pay the block average difficulty of those blocks, you'd have no buffers left for unlucky rounds.

Maybe this is just me not getting it ;-)

Another thing, the cron code port doesn't seem to say what the rounding is you are doing. You multiply the current found block difficulty with a config setting. That doesn't seem to reflect the block average proposed?

Overall I am not certain this would work well. It may be working if all rounds are unlucky but then it may just be an issue with estimating round shares. In which case PPLNS would probably better using found block shares instead of estimated difficulties.

Looking forward to hearing your comments.

**Comment by TheSerapher** [comment]
Okay it was indeed me being dumber than I should. PPLNS != PPS, sorry for that.

So if I understand correctly you look at ylur current last found block and simply multiply that blocks difficulty by your config setting. I'd rename 'blockcount' to multiplier so people don't get the impression it's related to averages.

The only issue I have here is the lack of change. The other systems were created to ensure a wide variety of shares across blocks to ensure people can't easily guess the pplns target and start hopping pools in order to fill X percent of that before jumps to another pool. You ndiff idea would allow hoppers to jump coins with a low change rate of block difficulties or coins that if changed they only change slightly. Even multiplying that by a random number will keep it guessable if you know the block difficulty and what the PPLNS target was.

Those are my two cents but I am not sold on the idea. Maybe others want to chime in. The change is fairly easy to do but I don't see the benefit yet.

**Comment by jonnybravo0311** [comment]
You've got the gist of it, yes.  Most of the BTC PPLNS mining pools use some flavor of N * diff.  For example, kano.is uses 5N.  P2Pool uses what amounts to 3N (they actually cap the share chain at a max 3 day age as well).  The value of the N*diff system is that you know your "ramp up" and "ramp down" times.  It's also effective at stopping a pool hopper simply by its nature.  Sure, you can jump in at the latter end of a block, but it doesn't really matter too much since there are N number of blocks worth of shares prior to you showing up.  Even if you continually do that, you're not really going to benefit since it's always going to be those total N*diff shares in the payout calculations.

With the currently available choices, you will gravitate towards a 1N payout (convergence around 100% luck) at least from a BTC mining perspective.  Wouldn't that be far more susceptible to pool hoppers?  With some of the other coins out there that have ever-changing difficulties, then the already available choices for PPLNS payouts should continue to suffice.

Anyway... those are my 2 bits :)

**Comment by TheSerapher** [comment]
I am closing all old feature requests and ideas since it doesn't seem that anyone is doing a PR against those anyway. Since I won't have the time, no need to keep these ideas open if they are not eventually being implemented.
