### ISSUE TITLE
Theme Check during Upgrade

### ISSUE THREAD

**Issue by akuma6099** [MPOS/php-mpos#2491]
I upgraded from 0.0.6 to 1.0.1 and redid my configs. Upon navigation to the main page I received a completly white screen. No page source at all. After various testing I narrowed it down to the following setting in SQL:

POOL.settings('website_theme', 'mpos')

Simply deleted it and everything popped up like normal. Maybe you could add a check in one of the upgrade SQLs for theme mpos and delete it if found. Hope this helps!

**Comment by TheSerapher** [comment]
This is a long time ago and even though this is valid it was covered in the upgrade notes back then (on IRC since we had no official releases yet). Automatic SQL upgrades didn't exist then so we couldn't do it automated.

Good thing you posted though since others will be able to find your answer now :-)
