### ISSUE TITLE
Estimated Earnings Wrong for PPLNS

### ISSUE THREAD

**Issue by jonnybravo0311** [MPOS/php-mpos#2492]
The calculation for estimated earnings is based on the number of shares since the last block was found.  That's not correct for PPLNS as the number of shares could be prior to when the last block was found, or after the last block was found.

Example using a fixed number of shares from config: `$config['pplns']['shares']['default'] = 100000000;`

If I found a block 50000000 shares ago, I'm not considering the 50000000 shares from the previous block find in my estimate calculation.  If I found a block 150000000 shares ago, I'm incorrectly including the extra 50000000 shares since the previous block find.

To fix this, we need to understand how many shares need to be fetched - both from the shares and potentially shares_archive tables.  This of course, depends on the PPLNS configuration.  If it's fixed, then you need to get that number of shares.  If it's block average, then you need to get that average.  Pseudocode follows:

`
if (getSharesToConsider(payout_method) <= getTotalSharesFromShareTable()) {
  roundShares = getSharesFromSharesTable();
}
else {
  roundShares = getSharesFromSharesTable() + getRemainingSharesFromSharesArchiveTable();
}
`

Once you have the appropriate valid/invalid shares for a true PPLNS round, then the existing code should work just fine to calculate the estimates.

**Comment by TheSerapher** [comment]
I'll be honest, I haven't done any real in-depth coding on MPOS anymore for a while so I'll trust your analysis on this :-D

Thinking about how this would work, this may have one impact on the system: Performance. We have to gather a lot of data in order to calculate a more appropriate estimate which isn't just based on the current round but includes all shares that need to be looked at. I am not entirely sure this is the case, but that may mean looking at a lot of data to get an estimate.

I'll keep this open for someone to look at and maybe create a pull request that can be tested by others. I will not be able to code this myself due to lack of time.

**Comment by TheSerapher** [comment]
I am closing all old feature requests and ideas since it doesn't seem that anyone is doing a PR against those anyway. Since I won't have the time, no need to keep these ideas open if they are not eventually being implemented.
