### ISSUE TITLE
admin account has been lockout due to unknown reason

### ISSUE THREAD

**Issue by jeong760** [MPOS/php-mpos#2500]
Dears,

I was create a MPOS admin account and start solo mining with 5 of SP20 miners but after some minutes later suddenly web admin account has been lockout. so whenever I am trying to logon to web portal using email address it says that " account locked please check your email for detail unlock." 

But I didn't setup an email server for MPOS so I don't know how I can reset or recovered it.

Regards,
John Ahn

**Comment by TheSerapher** [comment]
Can't say why you have been Locke four but simply changing the column in the accounts table should unlock your account. I recommend using mails though since it also allows for two factor authentication.

Lockout usually happen with failed passwords so I'd check nobody tried to login with your account (maybe even by accident).

Closing since not an actual bug/issue.

**Comment by jeong760** [comment]
@TheSerapher  thank you I was solved this issue when after I posted this. I was connect a MySql DB and directly editing its row.. 

But I am sure never entered a worng password many times. just I logon usign my amdin account and after I was clean up histoy on my browser. and after it was locked.

**Comment by TheSerapher** [comment]
If the failed password row and failed pin rows both don't show any entries maybe this was done by the miner software due to failed shares. Some allow user banning to avoid flooding a server with invalid shares. E.g. A misconfigured client could spam invalids.

MPOS doesn't lock on a whim so that's what I'd think may have happened, depending on the stratum used and its settings.
