### ISSUE TITLE
Shares being credited properly but not showing up in "actual shares" stats

### ISSUE THREAD

**Issue by fedaykinofdune** [MPOS/php-mpos#2508]
Not sure what's going on here, I've never seen this happen. Everyone is being properly credited for shares submitted, but under actual shares, is a big fat zero.. Pool hashrate is showing either zero or like .06 k/h.. I'm running MPOS with vanilla (zone117x) NOMP as my stratum backend on an x13 coin called MartexCoin. I have vardiff set to start out at .001 up to max 1. In MPOS config, is it possible to config it to x13? I have it set to scrypt. That's all I can really think of as the culprit right now, and don't want to break anything un-necissarily as people are mining at the present.

Any input?
Thanks!

**Comment by TheSerapher** [comment]
This isn't a script coin. Hence all hashrate calculations will be off and not valid. Shares are also 0 due to the low diff. Try using X13 since that's what the coin is. It's mainly for display purposes on the frontend unless you run PPS (which most of the time you shouldn't). So change it see if it works.

**Comment by fedaykinofdune** [comment]
Just got an "unable to load coin class definition x13" error when I changed it. This is the first non-SHA256 or scrypt MPOS pool I've ever done so it is new territory for me. I haven't messed the MPOS $config['difficulty'] = 20 setting though. Would that at least even things out with "expected shares" vs "actual"? Sorry for this, I've been out of the pool business for a while and I've forgotten so much.

**Comment by TheSerapher** [comment]
Sorry, X13 doesn't exist but you can try X11, this may be similar to X13 (or even the same when it comes to calculations). No guarantees though until someone looks into X13 in detail and see if it's working in MPOS with a simple coin definition.

Difficulty has become obsolete since all stratums support adding the diff for each share. It's used as a fallback for those that don't. You can safely ignore this.

**Comment by TheSerapher** [comment]
Just checked and it seems that X11 can be used for X13. Same target bits for both.

**Comment by TheSerapher** [comment]
FYI if you checkout the development branch `git checkout development; git pull` you can try out the X13 class. It's just a copy of the X11 but at least you can use the x13 algorithm in the config :-)

**Comment by fedaykinofdune** [comment]
Oh, alright! Thanks much.

**Comment by fedaykinofdune** [comment]
That worked great.
