### ISSUE TITLE
Setup Guide for MPOS using VPS *** DASHCOIN

### ISSUE THREAD

**Issue by hiroshi2701** [MPOS/php-mpos#2524]
Hi there, 

I'm looking for a guide to create my own MPOS mining pool on VPS. Can I used this guide 
https://github.com/MPOS/php-mpos/wiki/Quick-Start-Guide? 

If so, where can I add the step in setting up VPS for MPOS in that quick start guide? 

Thanks so much guys. Any help will be appreciated. :) 

Regards, 
Mark

**Comment by TheSerapher** [comment]
VPS or Root Server is pretty much the same thing - in the end you install MPOS the same ways. It may be a bit different for VPS but a VPS is not suitable for any larger installations due to lacking performance (especially on larger DB queries later down the road).

The Quick Start Guide should be kept as generic as possible. If you run a VPS and wish to install it, you should be capable in doing so by just using the Quick Start Guide. If a VPS is that special I'd recommend it's own article and using references to the Quick Start Guide when possible.
