### ISSUE TITLE
scryptn expected share much too losw

### ISSUE THREAD

**Issue by cryptobay** [MPOS/php-mpos#2525]
I have setup a pool with a scryptn coin in MPOS and as a stratum i am useing unomp.
Without any changes the expected shares are about 40 shares. Because, the difficulty on unomp stratum is set to 0.01 the generated shares are so tiny, that they are not visible on the MPOS frontend until they get rounded to 1.
I have added the MPOS multiplier of 1024 to the coin.json on unomp. No everyuser is "creating" shares and the shares are visible in the MPOS. Sadly, the expected shares are still 40 so the rounds are "closed" with about 400,000% of expected shares :/
on difficulty setting of global.inc.php i have 16, does this value here matter? I have seen, that most stratum proxies dont require this setting anymore?

I hope you understand what i was trying to say and i also hope, that you can help me out :)

**Comment by TheSerapher** [comment]
Difficulty setting in MPOS was a fallback value used for Stratum servers that did not insert the share difficulty. Since all modern Stratums do this it's deprecated and could probably be removed altogether from the code. I keep it in for Legacy purposes :)

NOMP only adjusts share difficult so MPOS will see them higher than they really are. This is not really doing much since MPOS itself still sees all normal difficulties for blocks - hence your high rounds.

You can adjust MPOS though to reflect the proper difficulty precision by changing your coin class and do something like in X11: https://github.com/MPOS/php-mpos/blob/master/include/classes/coins/coin_x11.class.php#L11

Don't forget to change how NOMP submits shares since those will be far off then :)

**Comment by cryptobay** [comment]
Wow, very fast reply thank you :)
Is it possible to change the displayed shares? For example the miners are submitting shares on a base of 0.0002 of a "complete" share. So if i could change the user shares, to actually display not only "1" but "1.00000". I hope you understand what i mean :)

**Comment by TheSerapher** [comment]
No since we are submitting 0.0002 as the share difficulty which is the actual value. Otherwise you are just counting shares, not their difficulties, which leads to discrepancies between what the miner sees and actually does.

Share counting was removed ages ago for that reason. It looks funny maybe, but thats rather a coin specific issue than something I'd work around in MPOS. Shouldn't be a huge issue though, just some visuals.
