### ISSUE TITLE
Adding coin support (add coin class)

### ISSUE THREAD

**Issue by ghost** [MPOS/php-mpos#2531]
Hi everyone.
How can we add a new coin to MPOS or support to an algo. for example blake2b or ethash, its just by creating a "coin class" or are more step to follow.
Thanks.

**Comment by khoubaibc** [comment]
Hi everyone,

any solution to add Equihash

**Comment by ripichipi** [comment]
Hi @khoubaibc I am working in a fork of NOMP to achieve that. If I make any progress I will let you know.
Regards

**Comment by GQM** [comment]
I believe I have a working coin class for equihash tested on https://pool.cryptobroker.io/zcl

Just working out some of the static statistics classes found for calculating expected shares so I can submit a PR

Any suggestions on how I can call the config.algorithm var I need in https://github.com/MPOS/php-mpos/blob/master/include/classes/statistics.class.php#L137 been a while since I've used PHP

**Comment by TheSerapher** [comment]
If you change the statistics, make sure it doesn't affect any other implementations and is as generic as possible :-) Especially because shares are a very tricky business and as soon as you get into the pay per share system, this has to be 100% accurate (otherwise you over- or underpay miners when using PPS). You may notice this is not a trivial change to adjust how shares are calculated and can potentially affect other users, so be certain that your changes are not touching any other users pools.

To answer your question, it depends what you are trying to do.

**New Coin Class and Base Class updates**
If you added a new coin class setting, you have to add a get function to the base class and return the value set. Target bits is a good example since it's always used:

Set a default value in the base class that works for all coins that hasn't set your specific value via a custom coin class:
https://github.com/MPOS/php-mpos/blob/master/include/classes/coins/coin_base.class.php#L18-L19

Implement the get method so you can call it in the statistics class:
https://github.com/MPOS/php-mpos/blob/master/include/classes/coins/coin_base.class.php#L21-L26

**Existing or new config setting**
This is how you'd access a new config setting inside the statistics class.

Create a new setting in the config file, e.g.:
https://github.com/MPOS/php-mpos/blob/master/include/config/global.inc.dist.php#L237

Access it in a class:
https://github.com/MPOS/php-mpos/blob/master/include/classes/statistics.class.php#L233

**Comment by GQM** [comment]
@TheSerapher thanks for such a detailed explanation. I believe I'm close and did most of the changes inside of a custom coin class.

I will do my best to keep things as generic as possible and only change things "if" config.algorithm == equihash which I found to be a lot different then other coins. My changes seem to work fairly well with the z-nomp stratum pool which was forked from nomp but I don't really have much else to base my changes off of as I notice some pools expected shares are much higher then what I'm calculating.

I'll try and get the changes submitted this weekend for others to have a look over and we can see if I'm on the right track ;)

**Comment by TheSerapher** [comment]
If you now react on the algorithm just for a single coin class, maybe it would be better to find a more generic implementation in the statistics (and potentially other) class. I'd wager there are quite a few coins that work out of the ordinary way nowadays (it's been a few years since I stopped on crypto coins ;-).

Take for example something like this: https://github.com/MPOS/php-mpos/blob/master/include/classes/statistics.class.php#L233

Even though this is an old function, it shows what we are trying to accomplish. Allow calculating the hash rate based on share difficulty, if not set in the table row use the difficulty set in the configuration.

Since this is a simple math function, we could remove it from the SQL statement and use the coin class to calculate the result. By adding a default function that matches this SQL statement and running it through the coin class, we have full control on how this is calculated.

I'll admit, this is a MAJOR change (remove calculations from SQL, export into coin class, change everything to calculate using the coin class, return the data) but it's also a really cool one giving more flexibility on how things are calculated based on the coin algorithms. And setting the base class to what we already have in the SQL statements will ensure it still works for all existing coins and implementations.

I am probably asking a bit much here, but it's just something you could look into while changing a few parts on the code regarding share counts and estimations :-)

**Comment by GQM** [comment]
I agree :) That would be the best route to take and make everything dynamic based on the coin class. Will do my best to figure this out, been learning lots over the past month and always up for a challenge. Thanks for all the suggestions and pointing me in the right direction :)

**Comment by TheSerapher** [comment]
No problem.

And a heads up: If you start testing your changes, make sure to at least also test with a SHA256 coin and a Scypt and/or scrypt-N. Usually coins offer a test network that you can connect to where difficulties are much lower so finding blocks is much faster. If you want to be 100% sure, run old versions of the pool parallel to a new version and compare their outputs. And don't forget PPS - I can't stress enough how important it is that this works 100% correct :-) Estimates between versions should match or there is an issue someplace.

**Comment by GQM** [comment]
I think I may be close to having something working which makes the statistics dynamic using the coin class functions.

I've run into a small snag by which the `block` tables `shares` column uses BIGINT, my assumption was to force diff 1 shares be used.

z-nomp is using a VarDiff which currently I have not used the mposMultiplier capabilities since everything seems to work without this change. Only trouble is when mining on testnet I discovered that shares valued at 0.xx don't get inserted into the database causing the block statistics to be off.
 
https://dev-pool.cryptobroker.io/zcl-testnet/index.php?page=statistics&action=blocks
VS
https://pool.cryptobroker.io/zcl/index.php?page=statistics&action=blocks

I originally thought it was just a rounding error but after looking into how those tables produce the numbers I believe it to be due to this error.

Would changing the column type to FLOAT cause issues with PPLNS or PPS calculations if everything is relative?

Just wanted to get others thoughts before making to many changes.

**Comment by TheSerapher** [comment]
Good stuff! If possible post the references here for the code you had in mind (or sql file) and I go check it out later.

**Comment by GQM** [comment]
Essentially I just modified some of the statistics functions to call the coin class in a loop which adds the required value.

```  
  /**
   * Get our last $limit blocks found by height
   * @param limit int Last limit blocks
   * @return array
   **/
  public function getBlocksFoundHeight($iHeight=0, $limit=10) {
    $this->debug->append("STA " . __METHOD__, 4);
    if ($data = $this->memcache->get(__FUNCTION__ . $iHeight . $limit)) return $data;
    $stmt = $this->mysqli->prepare("
      SELECT
        b.*,
        a.username AS finder,
        a.is_anonymous AS is_anonymous,
        difficulty AS difficulty
      FROM " . $this->block->getTableName() . " AS b
      LEFT JOIN " . $this->user->getTableName() . " AS a
      ON b.account_id = a.id
      WHERE b.height <= ?
      ORDER BY height DESC LIMIT ?");
    if ($this->checkStmt($stmt) && $stmt->bind_param("ii", $iHeight, $limit) && $stmt->execute() && $result = $stmt->get_result()) {
        $aData = array();
        $count = 0;
        while ($row = $result->fetch_assoc()) {
          $aData[$count] = $row;
          $aData[$count]['estshares'] = $this->coin->calcEstaimtedShares($row['difficulty']);
          $count++;
        }
        return $this->memcache->setCache(__FUNCTION__ . $iHeight . $limit, $aData, 5);
    }
    return $this->sqlError();
  }
```

I'm still trying to figure out how to include a precision based on the `$share_difficulty_precision` value found in the coin class to avoid using a multiplier for the shares diff value.

Where is the amount of shares inserted into the block table? Is it based on this function:

https://github.com/MPOS/php-mpos/blob/b7b45eb580dfd7f683540b519a66e14d3fe8321d/include/classes/share.class.php#L76

Thanks again for any help/guidance you can provide

**Comment by TheSerapher** [comment]
That's how I would have done it. There are mor occurrences where some coin calls are needed but this looks correct.

https://github.com/MPOS/php-mpos/blob/master/include/classes/block.class.php#L239 that's where a Blocks shares are set, you should be able to find that class call in one of the cronjobs (most likely).

I wonder what the issue seems to be. I remember that X11 had very low share numbers so the frontend had to be tweaked to properly display values (shares really) and maybe hashrate too (doubt that though). So you'll probably find that in the JS API library or smarty templates.

It's funny to see how MPOS has grown. If I'd redo the hole software but stick to PHP I'll probably do a lot of things differently. Thanks for your help on improving a few things!

**Comment by GQM** [comment]
@TheSerapher I believe I figured out the issue. It was due to some of the columns being set to BIGINT causing any trailing decimals to be cut off when inserted.

I've change them to DOUBLE to avoid issues with floating point decimals when using SQL SUM() on FLOAT numbers.

I'm not that great with MySQL so wasn't sure if I needed/how to create an upgrade script for the changes but did update the base `sql/000_base_structure.sql` file.

Since making some of the changes I must have messed something up with statistics/round page and just debugging things now. Everything else seems to be working but also need to test PPLNS and PPS.

https://dev-pool.cryptobroker.io/zcl-testnet/index.php?page=statistics&action=round

I've managed to make most of the users hashrates dynamic based on the pools setting.

ie. https://dev-pool.cryptobroker.io/zcl-testnet/index.php?page=statistics&action=pool

Personally I want to eventually integrate MPOS into a Meteor application by using Apollo aka GraphQL to pull/update the frontend in near realtime ;) Figured I should learn how things work first and it seems to handle the backend fairly well :) Mostly going to focus on updating the frontend to be more responsive.

**Comment by GQM** [comment]
@TheSerapher I have shared my changes publicly, would appreciate any feedback you could provide. A lot of things are made dynamic but I still need to do some more testing and get the DB upgrade script working. Also wanting to move the estday calculations to the coin class but haven't gotten around to it just yet.

https://github.com/GQM/php-mpos/tree/development

**Comment by TheSerapher** [comment]
If this is a clean build just create a Pull Request against my Development branch and we can discuss changes and updates there :)

**Comment by GQM** [comment]
I will work on that tomorrow, currently almost 5 am where I am so going to finish up some last minute changes on my live pool before getting some sleep ;)

**Comment by TheSerapher** [comment]
Welcome to my world :D One of the reasons why I had to withdraw from MPOS was time management. You can hardly say "no" if people run into pool critical issues during development phase, so a 3 AM bugfix wasn't uncommon.

Tales from the War aside, get some sleep, no rush!

**Comment by TheSerapher** [comment]
I am closing all old feature requests and ideas since it doesn't seem that anyone is doing a PR against those anyway. Since I won't have the time, no need to keep these ideas open if they are not eventually being implemented.

**Comment by cycleworm** [comment]
Hi @GQM have you been able to implement an additional algo like blake2b ?

**Comment by GQM** [comment]
@cycleworm I have been busy with launching my new exchange so haven't been very active in development. Implementing a new algo isn't that difficult if you have the Stratum pool that is compatible with MPOS, your just going to run into potential issues with the stats not reporting correctly. It's all relative though and shouldn't affect the overall operation. Best bet is to try it out on testnet and see what results you get then tweak the settings until you get more accurate stats. All mining pools are reporting rough estimates of stats based on the work/shares submitted.

**Comment by cycleworm** [comment]
Hi @GQM, thanks for your response. Are there any guides / tutorials or informations that you can recommend for getting started with creating an additional coin algo to an stratum mining pool?

**Comment by EugeneWebdev** [comment]
hello, TheSerapher
I would like to invite you for my job.
My job is to integrate ethash hashimoto into the MPOS.
I have some issues on there. when you are available on here, please ping me, thanks.

**Comment by TheSerapher** [comment]
I am neither maintaining nor doing paid or custom work for it anymore. Need to find someone else for it.

**Comment by YLXTechnologies** [comment]
> Hi @khoubaibc I am working in a fork of NOMP to achieve that. If I make any progress I will let you know.
> Regards

Did you ever achieve this? I really want to add ETC to NOMP
