### ISSUE TITLE
谁能告诉我怎么去解决它谢谢Findblocks disabled, new blocks will currently not show up in the frontend

### ISSUE THREAD

**Issue by wuhuaping** [MPOS/php-mpos#2536]
We are investigating issues in the backend. Your shares and hashrate are safe and we will fix things ASAP.

Findblocks disabled, new blocks will currently not show up in the frontend

Who can tell me how to solve it      
Web page fault
[information redacted]

**Comment by TheSerapher** [comment]
Please do not share personal information on Github. This is a bug tracker and not a help forum. If you need assistance find support in a forum of your choice.

You may just want to force run the cron (findblocks.php) but this could be caused by a hard fork in your blockchain. This is much more difficult to fix.
