### ISSUE TITLE
Feature request: Disable Login notification for certain IP addresses

### ISSUE THREAD

**Issue by blondak** [MPOS/php-mpos#2541]
Disable sending login notification for well-known IP addresses (eg. when I connect from home with static IP)

**Comment by blondak** [comment]
I think on users notification settings, because its related to the notifications. 

19. 1. 2017 16:03, 16:03, Sebastian Grewe <notifications@github.com> napsal/a:

**Comment by TheSerapher** [comment]
Sounds like a plan though I am not sure this really needs to be done. Even if you have a fixed address and it may make sense to whitelist, what if someone hijacks your session or browser and logs in via your account from your whitelisted IP or simple IP Spoofing? I'd still want to know that someone logged in because then I am sure it wasn't me.

Feel free to PR this if you feel this is necessary :-)

**Comment by TheSerapher** [comment]
I am closing all old feature requests and ideas since it doesn't seem that anyone is doing a PR against those anyway. Since I won't have the time, no need to keep these ideas open if they are not eventually being implemented.
