### ISSUE TITLE
Can't find shares.

### ISSUE THREAD

**Issue by UnsignedInt8** [MPOS/php-mpos#2546]
Hello sir.

There is an issue about prop payment. It can't run correctly.

![mpos_monit](https://cloud.githubusercontent.com/assets/15274326/22852343/2da25564-f075-11e6-8ac4-d4651922010a.png)

But the findblock log file and database seem right:

![logs](https://cloud.githubusercontent.com/assets/15274326/22852349/4b03014e-f075-11e6-9ea9-e0e697e17253.png)

![blocks](https://cloud.githubusercontent.com/assets/15274326/22852361/91440f4a-f075-11e6-8d0f-1e4f4b207d2e.png)

![mpos_info](https://cloud.githubusercontent.com/assets/15274326/22852367/b625e234-f075-11e6-988b-83c8be5f4573.png)

And this is the log file about prop_payout:

![prop_log](https://cloud.githubusercontent.com/assets/15274326/22852375/eeccad16-f075-11e6-955a-274f5913f4e6.png)

Could you please tell me where is wrong?

**Comment by TheSerapher** [comment]
Looks like that bock has already been paid out? Was there a hard fork on your blockchain? Hard to say why MPOS wants to pay this block again since it seems like it was paid out already (according to the blocks age I'd guess it was paid?).

I can't say for sure what your specific issue is, but you could also try marking that block as paid to users (since you are the only user nobody should be affected). I also strongly advice not to use the username 'admin' since it's too easy to guess.

**Comment by UnsignedInt8** [comment]
I think no blocks have been paid out because all blocks are not confirmed. And I'm using dogecoin testnet to test it.

![unconfirm](https://cloud.githubusercontent.com/assets/15274326/22852474/0e8d3592-f078-11e6-9e51-c258cd7648bc.png)

**Comment by UnsignedInt8** [comment]
I think it's not a bug of MPOS. 

If you have any idea to solve it, I hope you can tell me. Thank you.

**Comment by TheSerapher** [comment]
Did your mine a block against the coin daemon itself or even set the coin daemon to discover blocks on its own? Then MPOS would pick up a block but not find shares for it. Or maybe shares have been purged and can't be assigned to that block anymore?

If all fails, you can restart the pool from scratch with a new wallet to further test things.

**Comment by UnsignedInt8** [comment]
I've just deleted all database files, wallet files, cache files, and restarted all services. And it has the same problem.

![new](https://cloud.githubusercontent.com/assets/15274326/22852755/26c47b6a-f07e-11e6-9808-5e6768bdd161.png)

![dogecoin](https://cloud.githubusercontent.com/assets/15274326/22852762/5594f53c-f07e-11e6-800e-e5c7ed64ec8a.png)

**Comment by UnsignedInt8** [comment]
I've just launched the cronjob files again. 

![mpos](https://cloud.githubusercontent.com/assets/15274326/22852930/a2cf35f2-f082-11e6-9690-2a1b9f1e22b3.png)

![mysql](https://cloud.githubusercontent.com/assets/15274326/22852936/bf9d4d90-f082-11e6-8031-d54d8facef64.png)

Do you have any ideas about this problem, sir?

**Comment by TheSerapher** [comment]
No but i doubt it's something in MPOS ... I wonder where the shares for these blocks went and why they were not paid out. Maybe it's a settting in NOMP that does this? Maybe NOMP is handling payouts?

**Comment by UnsignedInt8** [comment]
No,, I disabled the payment feature of NOMP.

![nomp](https://cloud.githubusercontent.com/assets/15274326/22853034/93e1c69c-f085-11e6-9932-3ba716bd0cac.png)

**Comment by TheSerapher** [comment]
Have you checked the shares table that those shares exist? It logs the share count and share_id for each block, so there must have been shares in the database when the block was discovered. Somehow during payout, those shares can't be found anymore so the payout fails.

**Comment by UnsignedInt8** [comment]
I have solved that problem. I'm sure it's not a bug of MPOS. :)

I launched 5 docker containers, one for memcached, one for redis, one for mysql, one for MPOS and one for UNOMP. All those containers link each other via socket. And MPOS can't find shares. But I don't know why. :(

At last, I reinstalled all components on my server, not in docker container. And the MPOS works fine. 

Thank you sir.

**Comment by TheSerapher** [comment]
To be honest, MPOS and Mining is really not the best to run in Docker. MPOS maybe, since it's just connecting to a DB and a Memcache (at least the memcache can also be docker) but depending on the mining activity you will need a hardware based database. All these fancy statistics in MPOS come at a price, without a relational DB and timestamps things like PPLNS wouldn't work.

But great you figured it out :-) And we have it posted here for others to review if they run into issues.
