### ISSUE TITLE
API hashrate units inconsistent

### ISSUE THREAD

**Issue by ADumaine** [MPOS/php-mpos#2555]
I just made getpoolstatus calls to two different pools and found the hashrate numbers are different from each.  And hashrate is text while nethashrate is a number.

It would make much more sense to provide in the same units.

Can the API provide add the units as a key pair{"units":"kSol"}?  The developer can then make the calculation to convert as needed.

Right now I have to look on the web at the pool stats to figure out the hash rates and then hard code a conversion number for each pool.  And if the hash rates increase my guess is the units change. Very nasty.

```
{"getpoolstatus":{
  "version":"1.0.0","runtime":32.948970794678,
  "data":{"pool_name":"ZEC.suprnova.cc",
    "hashrate":"4151979.622638",
    ...,
    nethashrate":76965723000}}}
```
Pool hashrate is in sol/s
Nethashrate is in milli-sols/s? (divide by 1000)

```

{"getpoolstatus":{
  "version":"1.0.0","runtime":42.762041091919,
  "data":{
    "pool_name":"zcl.suprnova.cc",
    "hashrate":"2629982600.4146",
    ...
    "nethashrate":8044247000000}}}
```
Pool hashrate is in milli-sol/s (divide by 1000)
Nethashrate is in micro-sols/s?  (divide by 1,000,000)

Also is there any way to provide instructions for sites that would not mind patching a file, but for some reason are not updating their whole site to the latest version?  I noticed suprnova is still on 1.0.0.

Thanks!

**Comment by TheSerapher** [comment]
Since every coin does whatever they feel like when returning those values it's just going to be a workaround for issues from the RPC itself. Since every coin is different and just from the values alone we can't decide on the hashrate unitnin place, I doubt this is going to be added to MPOS. 

And to make things worse it seems that your coin is using a different hashrate string as well?

Maybe someone can take a stab at it but I don't see a generic solution for all these coins out in the wild.

If sites aren't updating that's sad but they could easily grab the file changes using Github tools (diff between versions of the entire project or just the diff between versions for a file). I see no reason to supply patch files in addition to what Github allows you to do.

**Comment by ADumaine** [comment]
I did not realize that MPOS simply passes through whatever a coin provides.  Yet in the UI the units are displayed, although sometimes inconsistently.

Take a look at https://zec.suprnova.cc/index.php?page=statistics&action=pool.
In the left column under Pool Hashrate, the Pool Hash is 4,369 kSols/s.
Scroll down to the General Statistics and the Pool Hash Rate is 4,369 H/s.

So it appears MPOS is performing calculations for display.  I would have to guess that the assumption is that the coin returns data in hash/s and is converted for display. Unless the units are configurable by the pool owner?

The  API for the zec site returns a value in Sols/s.

When checking the same UI items on https://zcl.suprnova.cc/index.php?page=statistics&action=pool the units match.  But the MPOS API returns a value multiplied by 1000.

Why is it correct (Sols/s) in the UI but not in the API? Why is it multiplied by 1000?

If MPOS is not correctly interpreting and displaying hash units, can we trust the other data, especially any calculations that rely on it?  I also found the projections for coins and BTC per day in the Contributer Hashrates were way off (overstated by 40% in some cases), but that is another issue. 

Other pools (flypool) return values like {"hashRate":"34.8 MH/s"}.  I thought it would be a simple addition to add the units to the API rather than changing the way current data is provided as there may be applications that are relying on the API data the way it is.  Always supplying it in Sol/s would be another way to approach it.

As for sites that are not updating versions, might this be because the entire pool would have to go offline to upgrade (please correct me if I am wrong)?  Wouldn't that effect the entire network and potentially cause miners to switch pools? I can see why a pool owner would not want to upgrade if there is not a way to hot upgrade or at least a way to patch certain issues.  And by patch, I simply mean description and instructions on the issue, how to update certain files and point to the source on github. This would obviously only work for functionality that does not depend on or affect core processes. like perhaps the API or display issues.

I am not a coin developer or a pool operator.  I am working on applications that consume the data available from pools and exchanges for people who are discovering crypto and want to jump in.  It is a pain writing code to interpret API data from each different type of site, let alone discovering inconsistencies in pools that use the same software but provide different units of data for different coins.  I was just hoping for some consistency....

**Comment by TheSerapher** [comment]
Consistency is exactly what's missing at coin RPC level and won't be achieved in MPOS. I do not feel that MPOS is responsible to convert consistent hashrate s from whatever the pools supply. What you are seeing on various pools at customizations to MPOS to allow coins to work somehow since they don't follow any generic way to do things.

I can understand your gripe with this but simply moving this a level away from applications into the MPOS API would just mean a lot more work in MPOS itself to start support all those different RPC interfaces out there. Basically exactly what you are doing :-)

It has always been a gripe of mine that there was no consistency across coins with only quick profits in mind and not having any real great new ideas. As you see, people make things work but I have yet to see PRs back to MPOS that would allow for a generic implementation of new and old coins. And to be honest I am not seeing a way to do it. I simply lack any time besides work and family to continue such a big project as coin mining has become. But at the same time I have yet to see another tool that does it as well as MPOS (with other third party tools to make it possible of course). Ever so often a new tool crops up but I am guessing they realize after a while that there is simply no consistency which makes development a constant running after coin implementations. 

And to answer your upgrade question: those are usually seem less upgrades and can be done in short timeframes - mining shouldn't be affected since that's run via Stratum and only inserts shares to the shares table. The reason why pools never upgrade: affromentioned coin customizations. Many go very deep in the code which makes upgrades, even if I'd supply patch files, a tedious task since they'd have to check for all conflicts and fix those.

It's been years since I stopped active work on MPOS and seeing youbare running into the exact same issues I did just shows how things have worked out :-/

I am afraid there won't be a fix on MPOS for this.

**Comment by TheSerapher** [comment]
Forgot to comment on that hashrate issue for hashrate calculations and estimates: exactly the same issue. The underlying algorithms I supplied will work only for exactly those implemented in the reference way. Any coin diverging from reverence implementation will not be correct, and estimated earnings and has rates will partially be completely off, depending on how well the code was hotfixed to support a coin. In cases where people don't know what they are doing and switch to a pay per share system for a pool, this may mean payments are completely off too. Again not much I'd be able to do by myself. MPOS does include a bit of work for coin algorithms but I never got around to make it generic enough to support any coin hashrate calculation available nowadays. There is a PR open with work to try to accomplish that but it's totally untested by me and I can't guarantee for its code to work as expected. Neither has there been any work on it in the past so I doubt it'll make it into the core.

Sorry if this sounds like a rant ;-) Coins have been growing like cancer and it was my main reason to stop working on this project. The irony in all this: MPOS allowed this in the first place. Starting up a new coin and allowing pooled mining right away was super hard before MPOS was done. Now anyone can do it with a bit of knowledge and that's been abused to a point where I have up running after yet another coin trying to make it big.

**Comment by ADumaine** [comment]
My next approach is to try getting some of the info from a block explorer site.

I appreciate your responses and tip my hat to you for building an application that had such a big effect in the cryptocoin world.
