### ISSUE TITLE
Donation Address not verified

### ISSUE THREAD

**Issue by HashUnlimited** [MPOS/php-mpos#2570]
Except having one or two support questions, me and probably others would really like to have a few coins transferred to the dev's pubkey :-)

we are simply not sure if this one, the one published on the frontend, is still alive, no action for years.... Lge95QR2frp9y1wJufjUPCycVsg5gLJPW8

**Comment by TheSerapher** [comment]
Yes that's still valid :-) Litecoin wallet from back then that's still synced.

**Comment by HashUnlimited** [comment]
Well now that this is clear, some coins are on the way ;-)

**Comment by HashUnlimited** [comment]
edit: if the wallet is from "back then" you might not see new ones as they are segwit from new -> old

**Comment by TheSerapher** [comment]
I got them .. thank you so much! +1

**Comment by HashUnlimited** [comment]
No need to thank, you did some work which enabled others to make a living out of it. I really appreciate that while being close to other alt coin miners running more than just one instance encouraging them to contribute as well. Just hoping you keep up the good work and hopefully getting us an update for the soon only wallet authentication method as well?

**Comment by TheSerapher** [comment]
It's been an underappreciated work for sure, but many things regarding crypto mining are. I guess it lies in the nature of it. People without money hope for the big break and only very few can make a living out of it. Donations really isn't a top priority for anyone.

Sadly I won't be able to further develop this software at all. I have left it available and try to help when I can but programming isn't on my roadmap for any foreseeable future. This was a side project which exploded with crypto mining but it was never intended to be the go-to solution for pooled mining.

I had planned to close this project but since I noticed it was widely accepted and modified everywhere, I left it open for forks and "historical data". Sometimes something can become clear when browsing through the history or simply using git blame ;-)

This project stays open and will accept PRs if they are thought out and are ensured not to affect any payouts (or rather the hard earned money of its users). They are also sparse, which probably is a result of the complexity of it and the dangers involved by modifying it.

Thanks again for the donation, it's not a common thing to receive around OSS development (and also not something I really expect from anyone!).

**Comment by HashUnlimited** [comment]
I read those lines, how we say in German - Mit einem lachenden und mit einem weinenden Auge - nevetheless there are just a few in crypto who's OSS is that popular to be copied, modded but left in shape by larger entities (don't want to use scam) like bcc & co. Wish you all the best mate, keep on rocking

**Comment by TheSerapher** [comment]
Yep, I am sure there are people that took the MPOS core, reshaped it using the template system and "sold" it as their own. But I was aware of that risk and that I won't be able to do anything about it. But such is live. Thanks, and all the best to you and your ongoing business! May the boom last for a while!
