### ISSUE TITLE
MySQL makes site run very slow

### ISSUE THREAD

**Issue by Bushstar** [MPOS/php-mpos#2599]
Our site has been up for years and when someone is looking at their transactions the site slows and sometimes times out.

What is the most appropriate way of truncating transactions without losing more than is needed?

I was planning on dropping transactions from before 2017 but wanted to check if this is sane and if there is a way to do it using the system. Like an config option for "Keep so many days worth of TXs" that I'm missing.

**Comment by ephieth0** [comment]
Have similar issues on database side. DB size is currently around 2GB, prop_payout cron is running about 200seconds. Statistic cron runs every minute. Running MySQL5.5 currently try to switch to MySQL5.6 for better performance due the fact that 5.7 has some issues.

How big is your DB?

**Comment by TheSerapher** [comment]
Prop Payout only inserts rows into transactions it doesn't read from them. If you are slow now that might mean you need a beefier system (depending on the amount of shares).

@Bushstar: There is no real way in MPOS itself to cleanup old transactions. Since they are considered of monetary value they were never cleaned. I guess as long as you only delete old and archived transactions you could be fine, others also use a cleanup that works that way.

**Comment by Bushstar** [comment]
Can you advise on whether the server specification below is suitable for the size pool we run?

We get 150 to 200 works running 500MH - 1,000MH Scrypt with a 2.4GB database. We use a $80 per month Digital Ocean Ubuntu 16.04 server running 8GB RAM with 4 CPU cores (Intel(R) Xeon(R) CPU E5-2630L v2 @ 2.40GHz).

If it's enough then we probably need to focus on optimisation but if not we will upgrade.

I understand the need to keep them as they are financial information and accounting software never intentionally forgets.

**Comment by TheSerapher** [comment]
More RAM and optimize MySQL Caching (percona toolkit has some good Tools for it). Disk should be SSD since pool payouts are also write heavy (deletes) not to mention inserting Shares =)

Due to the share Counts there isn't much room left to optimize on a DB or MPOS Code, especially with PPLNS payouts (requires meticulous tracking of Shares/times).

**Comment by scorpio18** [comment]
I have let's say a similar problem but with the cronjobs on a PPLNS pool.
Right now i have 4000 workers with a hash between 3 - 15 TH on scrypt algo the problems is the database is 6.7GB and just the shares_archive is 5.5GB , the thing is the tables_cleanup is taking 70 to 90 seconds to complete the thing is i'm running the maintenance cron each minute and i'm getting an e-mail each minute because of tables_cleanup taking to long to complete , the other problem is the pplns cronjob , same thing when a block is found the cron is complete in between 120 - 250 seconds , is there any way to optimize the database ? i have looked on the internet but still can't find a goof config , by the way i'm running 10.1.28-MariaDB-1~xenial

**Comment by TheSerapher** [comment]
More cpu power, more ram and ssd is your option. Also run a config checker for your DB to find ways to optimize memory usage. Not much else left to do other than switching to Prop. PPLNS is very DB intensive because it has to check two tables. A slow cleanup job indicates slow spinning disks or low bandwidth to them, a fast ssd will fix that.

**Comment by scorpio18** [comment]
I have Intel(R) Xeon(R) CPU D-1531 @ 2.20GHz 12 CPU cores with SSD and 32GB ddr4, that was my first option to chnage it back to prop but the miners won't like it because of the pool hopers who rent from nicehash :)
For the tables_cleanup cron i set it to run every 2 minutes so i don't receive each minute a mail with the "Cron seems to be running already
Process found in process table, aborting"  but now i receive mails because of the pplns cronjob

This is what i get from mysql tuner 

    MySQL started within last 24 hours - recommendations may be inaccurate
    Dedicate this server to your database for highest performance.
    Adjust your join queries to always utilize indexes
    Consider installing Sys schema from https://github.com/mysql/mysql-sys
Variables to adjust:
    join_buffer_size (> 4.0M, or always use indexes with joins)
    innodb_buffer_pool_instances(=15)
