### ISSUE TITLE
Why MPOS doesn't make an API for stratum?

### ISSUE THREAD

**Issue by shtse8** [MPOS/php-mpos#2604]
I can see many stratums which supporting MPOS are directly insert records to MPOS database.
It's terrible and once MPOS is modified the database structure. They need to update too.
I would suggest better to make an API for stratum usage.

**Comment by TheSerapher** [comment]
MPOS isn’t actively developed anymore, neither are many stratums that are still used. So even if MPOS offers an API to insert shares, stratums would have to be modified to use it. Also the shares table wasn’t really from MPOS and was just included for stratum to be used. It hasn’t been modified since it’s release. Last but not least an API would never be able to handle the shares pushed into it by a very busy stratum Server. We are talking thousands of shares per second on large installations, it just makes more sense for stratum to just insert shares itself than take that extra overhead of an API call to then insert a share.

In any case, MPOS isn’t developed actively anymore so you probably won’t see it happen.
