### ISSUE TITLE
[Feature Request] User Balance api

### ISSUE THREAD

**Issue by edmundhei** [MPOS/php-mpos#2627]
It will be nice that getuserbalance api will be available to user. According to this[https://github.com/MPOS/php-mpos/wiki/API-Reference](https://github.com/MPOS/php-mpos/wiki/API-Reference) getuserbalance require admin. Is it possible to make it available token as well?

**Comment by hossbeast** [comment]
getuserbalance can be queried by just specifying api_key, admin not required

**Comment by KevinBiomech** [comment]
Some of the comments in the codebase and the docs have been unchanged since
MPOS was new. It would be helpful to just plain rewrite the docs. I"m not
volunteering, simply due to time constraints, but if somewhat puts up a
wiki or starts such a project, I am willing to help. If it's already in
progress, point me at it :D

**Comment by TheSerapher** [comment]
I checked the code and it allows fetching balances for your own user ID or any user if you are admin. I updated the Wiki page, probably just an oversight on my part.

Most of the documentation is still accurate mostly because nothing has changed much since MPOS was written :D Feel free to update wiki pages if you see fit, they are accessible and editable by the community.
