### ISSUE TITLE
Instructions for adding new coin support

### ISSUE THREAD

**Issue by bgadmin** [MPOS/php-mpos#2633]
Hello, I've done some research and saw that it is able to add new coin to the MPOS, but there aren't any instructions on how to do it precisely. 

I would like to add ethereum, zcash and monero.

Could you please add instructions page to Wiki on how to add new coins?

Thanks !

**Comment by TheSerapher** [comment]
Coin implementation is very basic in MPOS. There was an idea to improve it but it never went into production.

In any case, if others have pointers on how to add these coins to MPOS I am sure they could share the information. I would assume that it requires quite a few core code changes to make them work, since they work differently than other (older) coins from when MPOS was originally written.

I would guess that a lot of RPC API calls have changed in coins, which aren't supported by MPOS. Those could be added in the bitcoin RPC class. Others may have changed mathematically so statistics have to be changed in order to show proper values.

It all depends on the coin really and is not a generic "go-to" solution that you could apply to all of them.
