### ISSUE TITLE
Got problem with manual cash out and auto cash out

### ISSUE THREAD

**Issue by datmacuibap** [MPOS/php-mpos#2645]
Hi Dev,
I got problem with manual cash out. I'm a pool operator, our miners can not get any coin when click button "Cash Out' at "cash out" section in "My Account".
I'm using newest release of MPOS. My pool is running ok, found blocks ok. miners can recieve their coins to your account, but can not withdraw (cash out) to their local wallet address!!

**Comment by TheSerapher** [comment]
Since the system has been stable for a while with a few issues (if withdrawal sums are too high the payouts will fail, you have to do it by hand then) you should check the log files why it's failing and then do payouts manually and park the user as paid in the database.

This project is not maintained anymore so this is the only hint I will give.
