### ISSUE TITLE
[Feature Request] make it possible to see global hash rate

### ISSUE THREAD

**Issue by jp26jp** [MPOS/php-mpos#2653]
The global hash rate would be for users that are mining on algo switching ports.

**Comment by TheSerapher** [comment]
I am not sure what global hash rate you are referreing to, but Network hashrate is already displayed in the pool dashboard for each user as long as a coin implements getmininginfo in their API.

In general, MPOS is not designed for algo switching ports but in the end multiple instances probably work with SSO to get the desired effect.

Cross-MPOS hash rate on the other hand isn't implmented and won't be since it's a rather bigger task to make MPOS instance aware.
