### ISSUE TITLE
Feature request: Add support for Hodlcoin - 1GB AES Pattern Search POW

### ISSUE THREAD

**Issue by Orava2** [MPOS/php-mpos#2661]
Hodlcoin is gaining popularity but the algo is missing from major pool sofwares.

Hodlcoin source code:
https://github.com/HOdlcoin/HOdlcoin

Algo:
https://github.com/HOdlcoin/HOdlcoin/blob/HODLCoin0.11.3/src/primitives/block.cpp
https://github.com/HOdlcoin/HOdlcoin/blob/HODLCoin0.11.3/src/patternsearch.cpp

Suprnova.cc is running MPOS and have a Hodlcoin support https://hodl.suprnova.cc/ but I did not manage to find 1GB AES Pattern Search POW from the source code.

**Comment by TheSerapher** [comment]
MPOS is not actively developed anymore, so no new coins will be added. Sometimes new coins use MPOS forks and add a specific coin to it, but most of the time there is no PR against upstream to add support globally or the changes for a coin are so drastic that no generic implementation exists.

You may find help out there, but core won't be adding new coins.

**Comment by TheSerapher** [comment]
And quick hint, have you tried running the coin at all? Many times MPOS will still work since it only looks at shares that have to be added by modified stratum instances. They do most of that work, MPOS only takes care of payouts.

As long as they don't do anything crazy in their API regarding basic coin functions, it may still be usable.
