### ISSUE TITLE
MPOS to replace the website that comes with https://github.com/electroneum/electroneum-pool

### ISSUE THREAD

**Issue by alexandre-romain** [MPOS/php-mpos#2696]
Hi TheSerapher,

Nice job you've done there. I played with MPOS & NOMP for a while and loved it.

I'm now running an electroneum pool but never managed to replace the 'built-in' website with MPOS.
I made some digging and saw that some pools (suprnova.cc for example) are using MPOS as frontend for Electroneum mining but it seems that their 'mpos version' is a bit different that what's available here.

Did they modify it themself ? Di you participate ? Any idea on how I could get a copy of this version or what to do to get it to work with the Electroneum pool ?

Thanks a lot !

**Comment by TheSerapher** [comment]
I have not done any work or support on MPOS outside this project so they must have done it themselves.

Try reaching out to them. Since they worked with MPOS they should be able to help you out. With most pools people tend to sit on their own code and market their own pool instead of spreading their work and ensuring a healthy economy ;-)
