### ISSUE TITLE
under pps mode but user couldn't check their earning status

### ISSUE THREAD

**Issue by chuanwc** [MPOS/php-mpos#2747]
recently i change my own pool from pplns to pps. but users report that they couldnt check their earning status anymore.The Statistical data is no longer updated.
I've also checked the transaction history,looks like the new block never showsup in the  Credit number.what i should do?

**Comment by TheSerapher** [comment]
Because blocks are not accounted for users, only shares. Each share gives them a payout, there are no rounds anymore.

Not sure if switching from PPLNS to PPS caused this but could be. In any case, you should be aware that PPS is a huge risk for pool owners and in general I advice against it unless you really know what you are doing.

Switching back also isn't possible once PPS was started, so you may have to reset the pool and start with a new wallet if you decide to get rid of it.

Screenshots would help here, no idea what the underlying issue is you reported.

**Comment by chuanwc** [comment]
May be i find the cause.
After the check i find that under PPLNS or PROP mode users earning status was marked with Credit in the table.but after the PPS mode it was marked with Credit_PPS.If that's the case what should i do?

**Comment by TheSerapher** [comment]
Nothing really, it should show in their transactions as Credit_PPS and they should gain coins. Slowly.

**Comment by chuanwc** [comment]
Yes，with the PPS mode in the transactions page users can check the detailed accounts by choose Credit_PPS.but there is still no statistical data in the  "dashboard/earning" page.Earning Reports show nothing but zero.

**Comment by TheSerapher** [comment]
Could you post a screenshot of that specific dashboard page and highlight it? Maybe I can check what's going on there.

**Comment by TheSerapher** [comment]
Hey @chuanwc any feedback on this?
