### ISSUE TITLE
getting full payout/transaction history?

### ISSUE THREAD

**Issue by ApolloMuses** [MPOS/php-mpos#2763]
I noticed that the `getusertransactions` only returns a limited subset (most recent) list of transaction data. would it be possible to return the full history? 

Here is the api call I'm making: 
`https://www2.coinmine.pl/dash/index.php?page=api&action=getusertransactions&api_key=xxxxxxxx&limit=1&start=500`

It doesn't matter what `start` I enter, the transaction always returns the same one. The `limit` however, works.

**Comment by ApolloMuses** [comment]
Looking at this: https://github.com/MPOS/php-mpos/blob/master/include/pages/api/getusertransactions.inc.php 
While the limit parameter works, the `start` parameter doesn't seem to work. Any ideas?

**Comment by TheSerapher** [comment]
Quickly checked the transactions class and from what I can see it should work. Start defines the last transaction you had and continues with limit. I would guess if you don’t have 500 transactions it will always start at the first?

I don’t see anything wrong in the code at least that would explain this.

**Comment by ApolloMuses** [comment]
Thanks for following up! Hmm do the transactions get automatically deleted?
Because the miner definitely have more than 500 but we can only pull the
most recent 100 for some reason.

**Comment by TheSerapher** [comment]
Not as far as I know. Some pools do delete old transactions because of the large volume ... it depends on the pool I guess.

I can’t test it myself right now but I am fairly sure it was tested when I wrote it 😃 

Keep unmindful when writing an app that fetching that many transaction can result in a huge amount of data. That’s why there is a default limiting only 30 set - most of the time a user won’t care about older stuff anyway. When it comes to taxes this data is useless anyway since they’d have to use the buy price at the time to file taxes - and that’s not available in MPOS.

**Comment by ApolloMuses** [comment]
Thanks Sebastian, 

The main pool I'm looking at is the Dash pool (coinmine.pl) and it uses this. Maybe they've limited it to 100 transactions. Because even though I change it up start to 10 or 100 or 1000, the transactions are always the same. 

For us it's more so for auditing purposes that needs such a level of detail. 

Thanks for your help.

**Comment by TheSerapher** [comment]
If you are auditing a pool with their knowledge and it’s required contact them directly. They must have hard coded the limit then. 

No problem - glad to clear this up.
