### ISSUE TITLE
This is more for information as I cannot find clear documentation.

### ISSUE THREAD

**Issue by lesjokolat** [MPOS/php-mpos#2779]
Can anyone point me to or provide me with advance breakdown for the following:

The MPOS pool requirements for json communications and order of input for jobs received from and sent to and from pool? All the components and standards  around:
Difficulty
Exrtranonce1
Extranonce2
Header
then mining submit.

I am developing a mining software and I am having challenges in determining errors in how MPOS based pools communicate.

I have read all sorts of stratum json documentation but still am having issues in properly connecting. Worker connection and authentication are ok.

Any help most appreciated.

Thanks

**Comment by TheSerapher** [comment]
MPOS has no api or json endpoint to post worker shares to. It’s using the underlying MySQL table shares which is filled by stratum or any other mining software. If you fill that table and use the workers table in MPOS for authentication you should be fine.

**Comment by lesjokolat** [comment]
Hi firstly thank you very much for taking the time to answer. So is there any way to get samples of such a worker table? will that tell me error messaging output and reason for things like, low difficulty shares, invalid job id, etc.

My issue I is in getting the pool software reason(my development can then be made to fix). As an example maybe my extranonce is wrong or I have the coinbase header incorrect..

Its that type of messaging that will help me.

thanks again

**Comment by TheSerapher** [comment]
You can find the table format I MySQL in the dB import file (in the repo). 

MPOS is not handing any mining errors. It’s not a mining software but a payout system for pooled mining based on data inserted by stratum.

I can’t help you further than that since I have no idea (anymore) how mining actually works. You’ll have to find other places to figure that out (like mining software out there and ask they code authors?).

**Comment by lesjokolat** [comment]
ok thanks for your help.
